### ISSUE TITLE
POST /v1/device groups with empty body returns 500 Internal Service Error

### ISSUE THREAD

**Issue by jillcary** [Azure/pcs-config-java#24]
# Type of issue

- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description

Service should return a more meaningful exception like Bad Request with a message saying "Request body is empty"

# Steps to reproduce

Request:
POST {endpoint}/v1/devicegroups
Body {empty}

# Expected behavior

Service should return Bad Request

# Current behavior
Service returns 500 internal server error

**Comment by zhang-hua** [comment]
close it since it has been fixed in PR #52 .
