### ISSUE TITLE
remove workaround code to fallback seed data resource file

### ISSUE THREAD

**Issue by zhang-hua** [Azure/pcs-config-java#56]
# Type of issue 

- [ ] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
Since PR #51 has fixed the resource file issue, the workaround code should be removed at below module:
.
https://github.com/Azure/pcs-config-java/blob/master/app/com/microsoft/azure/iotsolutions/uiconfig/services/Seed.java#L129

**Comment by ppathan** [comment]
Checked in
