### ISSUE TITLE
DevicegroupFilters returns NULL

### ISSUE THREAD

**Issue by swetha571** [Azure/pcs-config-java#60]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
Device group filters returns NULL

![image](https://user-images.githubusercontent.com/16091688/35015601-f4bae468-fac9-11e7-8b46-dbc2c1a641d7.png)

...

# Steps to reproduce 
1. Do the latest Cli deployement
2. Go to dashboard
3. Then go to manage filter flyout
4. See the field values returns empty.
5.Open the newtwork devtools and look for the devoicegroupfilters.

# Expected behavior 
...

# Current behavior 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* Java SDK: ...

# Code to reproduce the bug 

```
import org.junit.*;
import org.junit.experimental.categories.Category;

public class MyTest {

    @Test(timeout = 5000)
    public void TestToReproduceIssue() {
        // Arrange
        ...

        // Act
        ...

        // Assert
        ...
    }
}
```

**Comment by zhang-hua** [comment]
This issue is fixed.
